import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Container } from "react-bootstrap";

import "./globals.css";
import "./App.css";

import NavBar from "./NavBar";

import MyFooter from "./components/Footer";

import { badges } from "./data/badges";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        <main className="p-5">
          <Container>{children}</Container>
        </main>
        <MyFooter badges={badges} />
      </body>
    </html>
  );
}
